### ISSUE TITLE
LocalDateTime format

### ISSUE THREAD

**Issue by esiqveland** [calne-ca/subsonic-java-client#3]
Hello, thank you for making this! Been using this for a while now to build a subsonic java client!

I am having an issue with the `starred` and `created` fields.

They seem to be hardwired to use this adapter:
https://github.com/calne-ca/subsonic-java-client/blob/master/src/main/java/net/beardbot/subsonic/client/base/LocalDateTimeAdapter.java#L25

But a real value I see on the wire for starred is `2024-07-18T22:20:25.220976486Z`. notice the number of decimals after second period.

If you try to parse that with the adapter it does fail.

Worth mentioning that if we use `Instant::parse` it handles all three variants just fine 👍 

Hope you still maintain this! Best wishes!

**Comment by calne-ca** [comment]
Hi,
I'll try to fix that this weekend when I find the time.
Will notify you once it's fixed :)

**Comment by calne-ca** [comment]
I've just released 0.4.0 which should fix this. If there's still an issue feel free to reach out again.
