### ISSUE TITLE
Implement Starred2 call

### ISSUE THREAD

**Issue by esiqveland** [calne-ca/subsonic-java-client#4]
The call to `getStarred2` seems to be missing:

https://www.subsonic.org/pages/api.jsp#getStarred2

Would be very nice with an implementation for this in this client 👍

**Comment by calne-ca** [comment]
I've just released 0.4.0 which includes new API operations star, unstar, getStarred and getStarred2.

**Comment by esiqveland** [comment]
niiice, thank you!

This really helps in getting started with clients!
