### ISSUE TITLE
getArtistInfo2

### ISSUE THREAD

**Issue by esiqveland** [calne-ca/subsonic-java-client#5]
Hey, would you consider adding these methods as well?

- `getArtistInfo2`
- `getAlbumInfo2`
- `getAlbumList2`
- `setRating`

Thank you for the very helpful library!

**Comment by calne-ca** [comment]
I'll try to do that this week

**Comment by calne-ca** [comment]
I've implemented these methods in the latest release 0.5.0. The getArtistInfo / getAlbumInfo operations are hard to test since Subsonic depends on an external system (Last.FM) for those. If you face any issue feel free to create a new issue and I'll provide a bugfix release.

**Comment by esiqveland** [comment]
Nice!

I think these Params classes need to be public, otherwise I can not use them:
https://github.com/calne-ca/subsonic-java-client/blob/master/src/main/java/net/beardbot/subsonic/client/api/lists/AlbumListParams.java

**Comment by calne-ca** [comment]
Ah, probably was a copy paste issue, since there are internal param classes as well.
I've fixed it and put the changes into a new release 0.5.1
